apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/app: nginx
    spec: 
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        sadas